### ISSUE TITLE
Authentication using keyfile..

### ISSUE THREAD

**Issue by byeblogs** [AlessandroVaccarino/docker-mongodb-sharding#1]
Hi, i liked this mechanism, could you add example how to set authentication :)

**Comment by AlessandroVaccarino** [comment]
Hi @byeblogs, you can enable keyfile authentication following [this Mongo note](https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/)

To do it without changing Docker images, you've to:

1. Create a keyfile (at the beginning of startup.sh):
`openssl rand -base64 756 > ./mongo.key
chmod 400 ./mongo.key`

2. Edit Mongo config to use the keyfile, before starting containers. To do it, change docker-compose.yml adding the following parameter to "command" statements:
`--keyFile /srv/mongo.key`

3. Copy the file to the nodes just after starting them (after line 3 of original startup.sh):
`docker cp ./mongo.key  <container_name>:/srv/`
